### ISSUE TITLE
Does not work with middle click (open in another tab)

### ISSUE THREAD

**Issue by alexolog** [spasche/openinbrowser#12]
The dialog pops up but the document does not open

**Comment by alexolog** [comment]
Any chance of addressing it?

**Comment by spasche** [comment]
Works for me. Can you give more detailed steps to reproduce with some details about your environment (OS, version, ...)?

**Comment by alexolog** [comment]
This is a bit of a contrived example but it illustrates it.
1. Go to http://www.dafont.com/smoothie-shoppe.font
2. Click on the "download" button
3. Select open in browser as text
4. Works correctly.

However, if I middle-click in step 2 instead of left-clicking, the file will not open at all.

**Comment by spasche** [comment]
I just tried your example on Fedora 22 and Windows 8.1 and when I middle click the link, it opens in a new tab. Then, I see the "Opening ..." popup where I can open it as text. If I do so, it opens as text in the newly opened (background) tab.
If that's not what happens in your case, maybe you have some other extensions that could be conflicting.

**Comment by alexolog** [comment]
Thank you for the explanation, it helped find the issue.

TabMixPlus has a setting "Prevent blank tabs when downloading files" (http://tmp.garyr.net/help/#links) that automatically closes the opened tab.

**Comment by spasche** [comment]
Ok, so this can be closed.
