### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by rulatir** [spasche/openinbrowser#17]
I installed the add-on, but I am unable to discover how to use it.

There's this image on a webpage that pops up a Save As dialog when I right-click on it and choose "View image" (or "Show image" - I'm back-translating this context menu label from Polish). Same happens when I copy the image URL and paste it in the URL field in a new tab.

After installing the add-on the symptom is unchanged, and I cannot find any new UI provided by this add-on that would supposedly enable me to view the image in browser. In particular there are no additional entries in the image context menu, no additional icons anywhere, and the add-on has no settings.

**Comment by spasche** [comment]
Hi,

The UI is visible when the "Opening ..." dialog box opens after clicking a URL that the browser can't display or is marked as to be downloaded. For instance: http://telepathy.freedesktop.org/doc/book/examples/python_simple_presence/example.py. In the dialog box, there should be a "Open in browser as" item.

There is also a "View" > "View as" menu (press "alt" if the menu is hidden).
