### ISSUE TITLE
Add-on stopped working in Firefox 44

### ISSUE THREAD

**Issue by HighCommander4** [spasche/openinbrowser#19]
This add-on seems to have stopped working in Firefox 44. The "Open in Browser" option in the download
dialog is still present, but when selected, nothing happens (no new tab is opened for the file, nor does it appear in the downloads list).

It would be great to get it working again. This is one of my favourite add-ons; I use it mostly for viewing code files (commony .cpp extension) that people have uploaded as attachment to bugs in various bug trackers.

**Comment by spasche** [comment]
It should work in Firefox 44. Does it happen on all URLs? Maybe you have another add-on that is conflicting. I suggest trying in a clean profile.

**Comment by HighCommander4** [comment]
With further experimentation I discovered the following:

- The problem only occurs if you middle-click on the link (so as to open the file in a new tab), not if you left-click on it.
- Even that problem does not occur in a clean profile.

**Comment by HighCommander4** [comment]
I tried to figure out which add-on was conflicting, but then found that just disabling some add-ons and then re-enabling the same ones fixed the problem...

**Comment by HighCommander4** [comment]
In case anyone else has this problem: I believe I discovered the conflicting addon that was causing this. It was Tax Mix Plus, specifically its "Prevent blank tabs when downloading files" option. With that option disabled, Open In Browser has finally been working well for me!
