### ISSUE TITLE
Broken in Nightly

### ISSUE THREAD

**Issue by FatOrangutan** [spasche/openinbrowser#24]
Testing Firefox 53.0a1 (2016-12-20) with extension v1.17.

The dropdown looks like this and doesn't contain any entries.
![capture](https://cloud.githubusercontent.com/assets/8336638/21371003/dafe48b8-c734-11e6-8296-0e6a620b8e2d.PNG)

I get the following error in Browser Console:
![scapture](https://cloud.githubusercontent.com/assets/8336638/21371082/38a6b81a-c735-11e6-9447-6202349bf332.PNG)

This is likely related to the depreciation of for-each in [Bug 1293305](https://bugzilla.mozilla.org/show_bug.cgi?id=1293305). Would be great if this can be fixed.

**Comment by HighCommander4** [comment]
I see this too.

**Comment by neroux** [comment]
Fixed as of #26

**Comment by HighCommander4** [comment]
Should this be closed now that PR #26 has been merged?

**Comment by spasche** [comment]
Yes, thanks.
